name: reset
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:

  sdk: '>=2.12.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6595
  curved_navigation_bar: ^1.0.3
  ff_navigation_bar_lts: ^0.1.6
  syncfusion_flutter_calendar: ^20.2.43
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.6
  animated_text_kit: ^4.2.1
  firebase_core: ^2.4.1
  just_audio: ^0.9.30
  audioplayers: ^1.1.1
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  uuid: ^3.0.6
  jiffy: ^5.0.0
  file_picker: ^5.0.1
  image_picker: ^0.8.5+3
  video_player: ^2.4.7
  dotted_border: ^2.0.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
    - images/bookEmojis/
    - images/motivationimages/
    - login.png

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: images/fonts/MyFlutterApp.ttf


